language: objective-c
os: osx
osx_image: xcode11.2
notifications:
    email: false

env:
    global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=XlsxReaderWriter.xcworkspace
    - IOS_SCHEME="XlsxReaderWriter"
    - IOS_SDK=iphonesimulator13.2
    - IOS_DEST="OS=13.2,name=iPhone 11"

    matrix:
    - DESTINATION="$IOS_DEST" SCHEME="$IOS_SCHEME" SDK="$IOS_SDK" RUN_TESTS="YES"

cache:
  directories:
    - $HOME/.cocoapods/

before_install:
- gem install cocoapods-acknowledgements
- gem install cocoapods
- pod outdated | awk '{ if ( $1 ~ /^-/ ) { print $0 } }' | awk '{ if ( $3 != $5 ) { pod update $2 } else { print "No updated needed it for" $2 } }
- pod update

script:
    - set -o pipefail
    - xcodebuild -version
    - xcodebuild -showsdks
    - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c
