language: objective-c
os: osx
osx_image: xcode12.0
notifications:
    email: false

env:
    global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=XlsxReaderWriter.xcworkspace
    - IOS_SCHEME="XlsxReaderWriter"
    - IOS_SDK=iphonesimulator14.1
    - IOS_DEST="OS=14.1,name=iPhone 12"

    matrix:
    - DESTINATION="$IOS_DEST" SCHEME="$IOS_SCHEME" SDK="$IOS_SDK" RUN_TESTS="YES"

cache:
  directories:
    - $HOME/.cocoapods/

script:
    - set -o pipefail
    - xcodebuild -version
    - xcodebuild -showsdks
    - source bundle.sh
    - lbundle exex pod install
    - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test -enableCodeCoverage YES | xcpretty -c
